spring:
  # ????????
  mail:
    host: smtp.163.com
    username: lycmoons@163.com
    password: MVWFFe56fbasKFs9   # ????????????????????????

  # rabbitmq ????
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
    port: 5672

  # security ????
  security:
    # filter ????
    filter:
      order: -100
    # jwt ?????
    jwt:
      key: lycmoons
      expire: 7

  # mysql ????
  datasource:
    url: jdbc:mysql://localhost:3306/foodSafety
    username: root
    password: 543416Liu*
    driver-class-name: com.mysql.cj.jdbc.Driver

  # redis ????
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0